# Generated by Django 4.1.6 on 2023-03-03 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0009_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='status',
            field=models.CharField(default='', max_length=30),
        ),
    ]
